# Site settings
title: Kirk Wright
email: franklinkirkwright@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Hello! My name is Franklin Kirk Wright. I am currently pursuing an Honours Bachelor of Arts at 
  McGill University in Ecomomics with minors in Computer Science and International Development Studies.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://locahost:4000" # the base hostname & protocol for your site
github_username:  jekyll

# Build settings
markdown: kramdown
